// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// alltickStockModelDao is the data access object for the table hg_alltick_stock_model.
// You can define custom methods on it to extend its functionality as needed.
type alltickStockModelDao struct {
	*internal.AlltickStockModelDao
}

var (
	// AlltickStockModel is a globally accessible object for table hg_alltick_stock_model operations.
	AlltickStockModel = alltickStockModelDao{internal.NewAlltickStockModelDao()}
)

// Add your custom methods and functionality below.
