// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeAlltickRequestDao is the data access object for the table hg_finance_alltick_request.
// You can define custom methods on it to extend its functionality as needed.
type financeAlltickRequestDao struct {
	*internal.FinanceAlltickRequestDao
}

var (
	// FinanceAlltickRequest is a globally accessible object for table hg_finance_alltick_request operations.
	FinanceAlltickRequest = financeAlltickRequestDao{internal.NewFinanceAlltickRequestDao()}
)

// Add your custom methods and functionality below.
