// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeCodeDailyDao is the data access object for the table hg_finance_code_daily.
// You can define custom methods on it to extend its functionality as needed.
type financeCodeDailyDao struct {
	*internal.FinanceCodeDailyDao
}

var (
	// FinanceCodeDaily is a globally accessible object for table hg_finance_code_daily operations.
	FinanceCodeDaily = financeCodeDailyDao{internal.NewFinanceCodeDailyDao()}
)

// Add your custom methods and functionality below.
