// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeCodeDao is the data access object for the table hg_finance_code.
// You can define custom methods on it to extend its functionality as needed.
type financeCodeDao struct {
	*internal.FinanceCodeDao
}

var (
	// FinanceCode is a globally accessible object for table hg_finance_code operations.
	FinanceCode = financeCodeDao{internal.NewFinanceCodeDao()}
)

// Add your custom methods and functionality below.
