// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeKdjDao is the data access object for the table hg_finance_kdj.
// You can define custom methods on it to extend its functionality as needed.
type financeKdjDao struct {
	*internal.FinanceKdjDao
}

var (
	// FinanceKdj is a globally accessible object for table hg_finance_kdj operations.
	FinanceKdj = financeKdjDao{internal.NewFinanceKdjDao()}
)

// Add your custom methods and functionality below.
