// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeKlineDao is the data access object for the table hg_finance_kline.
// You can define custom methods on it to extend its functionality as needed.
type financeKlineDao struct {
	*internal.FinanceKlineDao
}

var (
	// FinanceKline is a globally accessible object for table hg_finance_kline operations.
	FinanceKline = financeKlineDao{internal.NewFinanceKlineDao()}
)

// Add your custom methods and functionality below.
