// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeRsiDao is the data access object for the table hg_finance_rsi.
// You can define custom methods on it to extend its functionality as needed.
type financeRsiDao struct {
	*internal.FinanceRsiDao
}

var (
	// FinanceRsi is a globally accessible object for table hg_finance_rsi operations.
	FinanceRsi = financeRsiDao{internal.NewFinanceRsiDao()}
)

// Add your custom methods and functionality below.
