// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeAlltickConfigDao is the data access object for the table hg_finance_alltick_config.
// You can define custom methods on it to extend its functionality as needed.
type financeAlltickConfigDao struct {
	*internal.FinanceAlltickConfigDao
}

var (
	// FinanceAlltickConfig is a globally accessible object for table hg_finance_alltick_config operations.
	FinanceAlltickConfig = financeAlltickConfigDao{internal.NewFinanceAlltickConfigDao()}
)

// Add your custom methods and functionality below.
