// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeScreeningDao is the data access object for the table hg_finance_screening.
// You can define custom methods on it to extend its functionality as needed.
type financeScreeningDao struct {
	*internal.FinanceScreeningDao
}

var (
	// FinanceScreening is a globally accessible object for table hg_finance_screening operations.
	FinanceScreening = financeScreeningDao{internal.NewFinanceScreeningDao()}
)

// Add your custom methods and functionality below.
