// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeBollDao is the data access object for the table hg_finance_boll.
// You can define custom methods on it to extend its functionality as needed.
type financeBollDao struct {
	*internal.FinanceBollDao
}

var (
	// FinanceBoll is a globally accessible object for table hg_finance_boll operations.
	FinanceBoll = financeBollDao{internal.NewFinanceBollDao()}
)

// Add your custom methods and functionality below.
