// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeKlineZigzagTrendDao is the data access object for the table hg_finance_kline_zigzag_trend.
// You can define custom methods on it to extend its functionality as needed.
type financeKlineZigzagTrendDao struct {
	*internal.FinanceKlineZigzagTrendDao
}

var (
	// FinanceKlineZigzagTrend is a globally accessible object for table hg_finance_kline_zigzag_trend operations.
	FinanceKlineZigzagTrend = financeKlineZigzagTrendDao{internal.NewFinanceKlineZigzagTrendDao()}
)

// Add your custom methods and functionality below.
