// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeZigzagMdDao is the data access object for the table hg_finance_zigzag_md.
// You can define custom methods on it to extend its functionality as needed.
type financeZigzagMdDao struct {
	*internal.FinanceZigzagMdDao
}

var (
	// FinanceZigzagMd is a globally accessible object for table hg_finance_zigzag_md operations.
	FinanceZigzagMd = financeZigzagMdDao{internal.NewFinanceZigzagMdDao()}
)

// Add your custom methods and functionality below.
