// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalFinanceKdjDao is an internal type for wrapping the internal DAO implementation.
type internalFinanceKdjDao = *internal.FinanceKdjDao

// financeKdjDao is the data access object for the table hg_finance_kdj.
// You can define custom methods on it to extend its functionality as needed.
type financeKdjDao struct {
	internalFinanceKdjDao
}

var (
	// FinanceKdj is a globally accessible object for table hg_finance_kdj operations.
	FinanceKdj = financeKdjDao{
		internal.NewFinanceKdjDao(),
	}
)

// Add your custom methods and functionality below.
