// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalFinanceConfigDao is internal type for wrapping internal DAO implements.
type internalFinanceConfigDao = *internal.FinanceConfigDao

// financeConfigDao is the data access object for table hg_finance_config.
// You can define custom methods on it to extend its functionality as you wish.
type financeConfigDao struct {
	internalFinanceConfigDao
}

var (
	// FinanceConfig is globally public accessible object for table hg_finance_config operations.
	FinanceConfig = financeConfigDao{
		internal.NewFinanceConfigDao(),
	}
)

// Fill with you ideas below.
