// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalFinanceMacdDao is an internal type for wrapping the internal DAO implementation.
type internalFinanceMacdDao = *internal.FinanceMacdDao

// financeMacdDao is the data access object for the table hg_finance_macd.
// You can define custom methods on it to extend its functionality as needed.
type financeMacdDao struct {
	internalFinanceMacdDao
}

var (
	// FinanceMacd is a globally accessible object for table hg_finance_macd operations.
	FinanceMacd = financeMacdDao{
		internal.NewFinanceMacdDao(),
	}
)

// Add your custom methods and functionality below.
