// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeDailyKlineDao is the data access object for the table hg_finance_daily_kline.
// You can define custom methods on it to extend its functionality as needed.
type financeDailyKlineDao struct {
	*internal.FinanceDailyKlineDao
}

var (
	// FinanceDailyKline is a globally accessible object for table hg_finance_daily_kline operations.
	FinanceDailyKline = financeDailyKlineDao{internal.NewFinanceDailyKlineDao()}
)

// Add your custom methods and functionality below.
