// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeAlltickResponseDao is the data access object for the table hg_finance_alltick_response.
// You can define custom methods on it to extend its functionality as needed.
type financeAlltickResponseDao struct {
	*internal.FinanceAlltickResponseDao
}

var (
	// FinanceAlltickResponse is a globally accessible object for table hg_finance_alltick_response operations.
	FinanceAlltickResponse = financeAlltickResponseDao{internal.NewFinanceAlltickResponseDao()}
)

// Add your custom methods and functionality below.
