// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalFinanceIndicatorDailyDao is an internal type for wrapping the internal DAO implementation.
type internalFinanceIndicatorDailyDao = *internal.FinanceIndicatorDailyDao

// financeIndicatorDailyDao is the data access object for the table hg_finance_indicator_daily.
// You can define custom methods on it to extend its functionality as needed.
type financeIndicatorDailyDao struct {
	internalFinanceIndicatorDailyDao
}

var (
	// FinanceIndicatorDaily is a globally accessible object for table hg_finance_indicator_daily operations.
	FinanceIndicatorDaily = financeIndicatorDailyDao{
		internal.NewFinanceIndicatorDailyDao(),
	}
)

// Add your custom methods and functionality below.
