// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financeConfigDao is the data access object for the table hg_finance_config.
// You can define custom methods on it to extend its functionality as needed.
type financeConfigDao struct {
	*internal.FinanceConfigDao
}

var (
	// FinanceConfig is a globally accessible object for table hg_finance_config operations.
	FinanceConfig = financeConfigDao{internal.NewFinanceConfigDao()}
)

// Add your custom methods and functionality below.
