// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financePlotDao is the data access object for the table hg_finance_plot.
// You can define custom methods on it to extend its functionality as needed.
type financePlotDao struct {
	*internal.FinancePlotDao
}

var (
	// FinancePlot is a globally accessible object for table hg_finance_plot operations.
	FinancePlot = financePlotDao{internal.NewFinancePlotDao()}
)

// Add your custom methods and functionality below.
