// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockIndicatorDao is the data access object for the table hg_stock_indicator.
// You can define custom methods on it to extend its functionality as needed.
type stockIndicatorDao struct {
	*internal.StockIndicatorDao
}

var (
	// StockIndicator is a globally accessible object for table hg_stock_indicator operations.
	StockIndicator = stockIndicatorDao{internal.NewStockIndicatorDao()}
)

// Add your custom methods and functionality below.
