// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// testFinanceDao is the data access object for the table hg_test_finance.
// You can define custom methods on it to extend its functionality as needed.
type testFinanceDao struct {
	*internal.TestFinanceDao
}

var (
	// TestFinance is a globally accessible object for table hg_test_finance operations.
	TestFinance = testFinanceDao{internal.NewTestFinanceDao()}
)

// Add your custom methods and functionality below.
