// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tgstatChannelCrawlerUrlDao is the data access object for the table hg_tgstat_channel_crawler_url.
// You can define custom methods on it to extend its functionality as needed.
type tgstatChannelCrawlerUrlDao struct {
	*internal.TgstatChannelCrawlerUrlDao
}

var (
	// TgstatChannelCrawlerUrl is a globally accessible object for table hg_tgstat_channel_crawler_url operations.
	TgstatChannelCrawlerUrl = tgstatChannelCrawlerUrlDao{internal.NewTgstatChannelCrawlerUrlDao()}
)

// Add your custom methods and functionality below.
